### ISSUE TITLE
TV 112 add on not working

### ISSUE THREAD

**Issue by bumehta17031947** [mrgsi/repository.glive#6]
TV 112 , TV 111 add on do not open any channels including sport since about 10 days, kindly fix it , at the earliest so that we can watch ICC world cup tournaments.

**Comment by mrgsi** [comment]
tvOne 112 runs on my setup. tvOne 111 crashed for some reason so I repacked it and pushed it as an update. It working for me know. I don't think this is an add-on issue as much as it is a dependency issue. I just haven't figured it out yet because, as I say, it's currently working for me. I will play around with it some more when I have time and see if I can get it to fail.

**Comment by bumehta17031947** [comment]
TV One, TVOne 112, TV One 111, are not playing any thing , i rechecked after your message , problem continues, If you want i can send log file but for that inform where to send, it may be because Tap Tv, Rb TV also not playing any thing pl fix it and help community , Regards

**Comment by mrgsi** [comment]
As I said, they work for me so the issue must be with either your installation, your device or your ISP blocking connections. I am not the developer, they were created by RACC a Japanese developer. If they work for me, I host them in my repo. You could try changing the settings to use Inputstream Adaptive. Other than that I wouldn't be able to guess what is going wrong. You may have better luck with Daddylive or MegaIPTV as they have international sports links as well.
