### ISSUE TITLE
TheTVApp is down (at least for me)

### ISSUE THREAD

**Issue by bjgood** [mrgsi/repository.glive#9]
Hi,
The TV App has been down for at least 3 days on my end. Is anyone else having this problem?

Thanks in advance.

Later...

**Comment by mrgsi** [comment]
Yep, it's a great add-on but highly unstable. I'm constantly watching for updates but eventually, devs will probably give up chasing their tail with this thing. As soon as I see an update, I will upload it to the repo.

**Comment by bjgood** [comment]
Thanks for the reply, mrgsi. :).

**Comment by ivarbrandt** [comment]
@mrgsi 

Do you know the location of the original repository for The TV App? 

I may try to just fix it myself.

**Comment by mrgsi** [comment]
Officially, no one really owns the add-on. It was actually made by mbebe but he wasn't interested in hosting or supporting it. I picked it up as a zip file and dropped it into my repo. That's why the developer is xxxxx instead of mbebe. He does that when he makes something he doesn't want to support. When it broke, Diggz picked it up and fixed it. He's been the only one fixing it ever since, when he has the time to do it. You can spot his handy-work when he uses versions starting with 420. However, he didn't add his name to it either. It's like a poor orphan with a lot of foster parents. lol
Daddylive started the same way, but The Crew decided to adopt it into their family which is why they put their name on it. 
If you want to fix it, feel free to do so. I'm sure the Kodi community would be grateful. Just know, it will continue to break which makes it frustrating to use and maintain. I doubt Diggz would complain if someone took it off his hands.

**Comment by mrgsi** [comment]
It's been fixed now and the repos updated to version 420.8.

**Comment by Shoninzo** [comment]
> It's been fixed now and the repos updated to version 420.8.

The update isn't showing up on my end

**Comment by ivarbrandt** [comment]
> Officially, no one really owns the add-on. It was actually made by mbebe but he wasn't interested in hosting or supporting it. I picked it up as a zip file and dropped it into my repo. That's why the developer is xxxxx instead of mbebe. He does that when he makes something he doesn't want to support. When it broke, Diggz picked it up and fixed it. He's been the only one fixing it ever since, when he has the time to do it. You can spot his handy-work when he uses versions starting with 420. However, he didn't add his name to it either. It's like a poor orphan with a lot of foster parents. lol Daddylive started the same way, but The Crew decided to adopt it into their family which is why they put their name on it. If you want to fix it, feel free to do so. I'm sure the Kodi community would be grateful. Just know, it will continue to break which makes it frustrating to use and maintain. I doubt Diggz would complain if someone took it off his hands.

Oh wow that addon has been through so much lol. 

I was about to take a look at the code but I guess now it's fixed. Thanks for keeping us informed.

**Comment by mrgsi** [comment]
> > It's been fixed now and the repos updated to version 420.8.
> 
> The update isn't showing up on my end

It's there, but repos can sometimes be stubborn in updating. Try going to the repo and clicking on Update to force it. I often use OpenWizard which has a "Force Refresh all Repositories" function that works well. It helps me check my updates to make sure they work, or I'd sit there all day waiting for Kodi to catch up. lol

**Comment by Shoninzo** [comment]
It's down again

**Comment by mrgsi** [comment]
I am not surprised. Even if it's fixed again, it will only last a few days.

**Comment by austreams** [comment]
yeah it’s not working again dammit, i love this addon thanks for everything you guys do!!

**Comment by Shoninzo** [comment]
> yeah it’s not working again dammit, i love this addon thanks for everything you guys do!!

Go install it on the diggz repo

**Comment by mrgsi** [comment]
Breaks too often to be useful.
